<?php /** @noinspection PhpUnused */
namespace
{
    const FRG_HTTP_STATUS_CODE_200_OK = 200;
    const FRG_HTTP_STATUS_CODE_201_CREATED = 201;
    const FRG_HTTP_STATUS_CODE_202_ACCEPTED = 202;
    const FRG_HTTP_STATUS_CODE_301_MOVED_PERMANENTLY = 301;
    const FRG_HTTP_STATUS_CODE_302_FOUND = 302;
    const FRG_HTTP_STATUS_CODE_400_BAD_REQUEST = 400;
    const FRG_HTTP_STATUS_CODE_401_UNAUTHORIZED = 401;
    const FRG_HTTP_STATUS_CODE_403_FORBIDDEN = 403;
    const FRG_HTTP_STATUS_CODE_404_NOT_FOUND = 404;
    const FRG_HTTP_STATUS_CODE_500_INTERNAL_SERVER_ERROR = 500;
    const FRG_HTTP_STATUS_CODE_503_SERVICE_UNAVAILABLE = 503;
    const FRG_DB_INSTANCE_PRIMARY = 0;
    const FRG_DB_INSTANCE_SECONDARY = 1;
    const FRG_DB_INSTANCE_TERTIARY = 2;
    const FRG_DB_INSTANCE_QUATERNARY = 3;
    const FRG_EXCEPTION_CODE_HTTP_NOT_FOUND = 'FRG_EXCEPTION_CODE_HTTP_NOT_FOUND';
    const FRG_ENV_DEVELOPMENT = 'development';
    const FRG_ENV_TEST = 'test';
    const FRG_ENV_STAGING = 'staging';
    const FRG_ENV_PRODUCTION = 'production';
    const FRG_MEDIA_TYPE_APPLICATION_JSON = 'application/json';
    const FRG_MODE_PHPUNIT = 'phpunit';
    const FRG_MODE_TASK = 'task';
    const FRG_MODE_WEB = 'web';
}
namespace castle
{
    const TEST = 'test';
}
